version: '3'

services:
  db:
    container_name: egresocovid19-db
    image: docker.uclv.cu/mongo
    env_file:
      - .env
    volumes:
      - ~/egresocovid19_db:/data/db
    restart: unless-stopped
  api:
    container_name: egresocovid19-api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: unless-stopped
