version: '3'

services:
  db:
    image: docker.uclv.cu/mongo
    env_file:
      - .env
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:80"
