[tool.poetry]
name = "egresocovid19"
version = "0.0.1"
description = "Egreso COVID-19 server implementation with FastAPI"
authors = ["Leynier Gutiérrez González <leynier41@gmail.com>"]
homepage = "https://github.com/codestrange/egresocovid19-server"
repository = "https://github.com/codestrange/egresocovid19-server"
documentation = "https://github.com/codestrange/egresocovid19-server"
readme = "README.md"

[tool.poetry.scripts]
egresocovid19 = "egresocovid19.cli:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
fastapi = {extras = ["all"], version = "^0.70.0"}
python-dotenv = "^0.19.1"
fastapi-restful = {extras = ["all"], version = "^0.3.2"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.5"
beanie = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = "^21.9b0"
isort = "^5.9.3"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.16.0"
mimesis = "^4.1.3"
pytest-depends = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
