
name: CI
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Set up Poetry 2.1.0
      uses: abatilo/actions-poetry@3.7.4
      with:
        poetry-version: 1.1.2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.9.0
      with:
        mongodb-version: 4.4
    - name: Run tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ACCESS_TOKEN_SECRET_KEY: ${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
        REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
      run: make tests
    - name: Upload coverage
      uses: codecov/codecov-action@v3
